project:
  type: website
  output-dir: "../../reports/rnaseq-crash-course"

website:
  title: "RNA-seq Crash Course"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - sidebar:computing
      - sidebar:pipeline
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/trev-f/rnaseq-crash-course
  body-header: |
    ::: {.callout-warning title="alpha stage warning"}
    This website is in its alpha stage.
    All pages are under active development and are subject to change at any time without warning.
    :::
  sidebar:
    - id: computing
      title: "Computing"
      style: "docked"
      contents:
        - href: computing/hpc.qmd
        - href: computing/isaac-ng.qmd
    - id: pipeline
      title: "Pipeline"
      contents:
        - href: pipeline/raw_fastqc.qmd
        - href: pipeline/trim_reads.qmd
        - href: pipeline/map_reads.qmd
        - href: pipeline/quantify_reads.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

